linters:
  enable-all: true
  disable:
    - gomnd
    - scopelint
    - maligned
    - golint
    - interfacer

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - errors # use "github.com/pkg/errors" instead
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  cyclop:
    max-complexity: 12
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake

run:
  deadline: 5m
